name: Feature Request
description: Suggest a new feature or enhancement for Mesh Master
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about your idea.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: What feature would you like to add?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this feature should work?
      placeholder: Describe your preferred solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions you've considered

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: true

  - type: checkboxes
    id: areas
    attributes:
      label: Feature Areas (check all that apply)
      options:
        - label: Memory/Context Management
        - label: Async Processing
        - label: Performance Optimization
        - label: User Interface/Experience
        - label: Configuration/Setup
        - label: Documentation
        - label: Testing/Debugging
        - label: Hardware Compatibility

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that helps explain the feature